language: node_js
node_js:
  - 12
branches:
  only: master
env:
  - EXTENSION_ID=nbiddhncecgemgccalnoanpnenalmkic
deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
      branch: master
